# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b253c3f18a0f21f4a70db6980ae849fa"
application_url = "https://room-quest-harbor-monroe.trycloudflare.com"
embedded = true
name = "App Therapy"
handle = "app-therapy"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_themes, write_themes"

[auth]
redirect_urls = [
  "https://room-quest-harbor-monroe.trycloudflare.com/auth/callback",
  "https://room-quest-harbor-monroe.trycloudflare.com/auth/shopify/callback",
  "https://room-quest-harbor-monroe.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "zaman-kingdom.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
